<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Http\Request;
use Sentry\Laravel\Integration;
use Stancl\Tenancy\Exceptions\TenantCouldNotBeIdentifiedOnDomainException;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        api: __DIR__.'/../routes/api.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
        then: function () {
            Route::middleware('web')
                ->group(base_path('routes/admin.php'));
        },
    )
    ->withMiddleware(function (Middleware $middleware): void {
        // Trust Traefik (and any Docker reverse proxy) so Laravel correctly
        // detects HTTPS from the X-Forwarded-Proto header. Without this,
        // $request->secure() always returns false behind a TLS-terminating proxy.
        $middleware->trustProxies(
            at: '*',
            headers: Request::HEADER_X_FORWARDED_FOR
                | Request::HEADER_X_FORWARDED_HOST
                | Request::HEADER_X_FORWARDED_PORT
                | Request::HEADER_X_FORWARDED_PROTO,
        );

        // ForceHttps is registered globally (prepend) so it runs on every request
        // BEFORE UseSiteHostHeader rewrites the Host/X-Forwarded-Host headers.
        // At that point getHost() still returns the raw incoming host (the real
        // public domain for browser requests, or the Docker-internal "app1" for
        // internal Next.js → Laravel SSR calls), so isInternalDockerHost() fires
        // correctly and SSR calls are never spuriously redirected to HTTPS.
        //
        // IMPORTANT — do NOT also add ForceHttps to the 'api' group.
        // After UseSiteHostHeader updates HTTP_X_FORWARDED_HOST, a second
        // ForceHttps run would see the real tenant domain, fail
        // isInternalDockerHost(), find no X-Forwarded-Proto on the internal HTTP
        // call, and emit a 308 redirect that breaks every SSR tenant/preview
        // API call.  The global prepend already covers all routes.
        $middleware->prepend(\App\Http\Middleware\UseSiteHostHeader::class);
        $middleware->prepend(\App\Http\Middleware\ForceHttps::class);
        $middleware->prependToGroup('web', \App\Http\Middleware\ForceHttps::class);

        $middleware->web(append: [
            \App\Http\Middleware\SetLocale::class,
        ]);

        // The page-unlock endpoint is called from the Next.js PasswordGate
        // client component via fetch(), which cannot include a CSRF token
        // generated by a separate Laravel session. The action is non-destructive
        // (unlocking a page the user already knows the password to) so CSRF
        // exemption is safe here.
        $middleware->validateCsrfTokens(except: [
            'pages/*/unlock',
        ]);

        $middleware->alias([
            'admin.auth'      => \App\Http\Middleware\AdminAuthenticate::class,
            'agency.admin'    => \App\Http\Middleware\EnsureAgencyAdmin::class,
            'member.auth'     => \App\Http\Middleware\MemberAuthenticate::class,
            'tenant.admin'    => \App\Http\Middleware\InitializeTenancyForAdmin::class,
            'tenant.module'   => \App\Http\Middleware\RequireTenantModule::class,
            'tenant.required' => \App\Http\Middleware\RequireActiveTenant::class,
        ]);

        // Tenant context MUST be initialized before SubstituteBindings so that
        // implicit route–model binding (e.g. `edit(Tour $tour)`) queries the
        // TENANT database, not central.  Without this, bound tenant models hit
        // `graficms` (central) and throw "table doesn't exist".
        //
        // Order enforced: AdminAuthenticate → InitializeTenancyForAdmin →
        // SubstituteBindings.  AdminAuthenticate first so the admin guard +
        // session are resolved before we pick the tenant.
        //
        // Core CMS controllers (Page/Article) use explicit findOrFail and are
        // unaffected; this only *additionally* enables implicit binding for
        // tenant-scoped models (Tours module).
        $middleware->prependToPriorityList(
            before: \Illuminate\Routing\Middleware\SubstituteBindings::class,
            prepend: \App\Http\Middleware\InitializeTenancyForAdmin::class,
        );
        $middleware->prependToPriorityList(
            before: \App\Http\Middleware\InitializeTenancyForAdmin::class,
            prepend: \App\Http\Middleware\AdminAuthenticate::class,
        );
        // RequireActiveTenant must run AFTER tenancy is initialized so it can
        // see whether a site is active.  Inserting it before SubstituteBindings
        // (and after InitializeTenancyForAdmin, added above) gives the order:
        // AdminAuthenticate → InitializeTenancyForAdmin → RequireActiveTenant
        // → SubstituteBindings.
        $middleware->prependToPriorityList(
            before: \Illuminate\Routing\Middleware\SubstituteBindings::class,
            prepend: \App\Http\Middleware\RequireActiveTenant::class,
        );
    })
    ->withExceptions(function (Exceptions $exceptions): void {
        Integration::handles($exceptions);

        // TenantCouldNotBeIdentifiedOnDomainException is a 404-level event
        // (unknown domain, Docker internal hostname, health-check pings …).
        // It is caught and turned into a clean abort(404) in
        // InitializeTenancyForPublicApi, but we also exclude it from Sentry
        // here so any edge case that still escapes never floods the quota.
        $exceptions->dontReport(TenantCouldNotBeIdentifiedOnDomainException::class);
    })->create();
